### ISSUE TITLE
Add a build option to disable pulseaudio dependency

### ISSUE THREAD

**Issue by Hummer12007** [desktop-app/tg_owt#30]

**Comment by gyakovlev** [comment]
in gentoo we can build and run it with apulse headers btw.

**Comment by Hummer12007** [comment]
Oh, you added a media-sount/apulse[sdk] dep. Thanks!

**Comment by gyakovlev** [comment]
no prob.
yeah, took a while to test all new webrtc stuff, but pulse is no longer forced, as all 3 tg related packages build with apulse[sdk] just fine.

it may not actually be using apulse lib, but simply falling back to alsa. anyway, it seems to be working fine.

**Comment by Hummer12007** [comment]
Hm, calls crash for me with this solution

**Comment by vitlav** [comment]
> Hm, calls crash for me with this solution
Can you send some details? Appropriate part of backtrace?

**Comment by Hummer12007** [comment]
Ack, will send this later today.

**Comment by Hummer12007** [comment]
```
(gdb) info threads
  Id   Target Id                         Frame 
* 1    Thread 0x7f4ec0a89640 (LWP 28023) __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
  2    Thread 0x7f4f33b39640 (LWP 23402) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4f2c0053c0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  3    Thread 0x7f4f30b33640 (LWP 23405) futex_wait_cancelable (private=0, expected=0, futex_word=0x5585e67592c8) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7f4f31334640 (LWP 23404) futex_wait_cancelable (private=0, expected=0, futex_word=0x5585e67592c8) at ../sysdeps/nptl/futex-internal.h:183
  5    Thread 0x7f4f2bfff640 (LWP 23406) futex_wait_cancelable (private=0, expected=0, futex_word=0x5585e67592c8) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7f4ef50c8640 (LWP 23423) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ec8004240, nfds=2, timeout=687) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7f4ece720640 (LWP 26880) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4f0c0108b0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  8    Thread 0x7f4f31b35640 (LWP 23403) futex_wait_cancelable (private=0, expected=0, futex_word=0x5585e67592c8) at ../sysdeps/nptl/futex-internal.h:183
  9    Thread 0x7f4f2a7fc640 (LWP 23409) 0x00007f4f36d2f7ef in __GI___poll (fds=0x5585e6927c10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  10   Thread 0x7f4ef6ddd640 (LWP 23420) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ed0003e10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  11   Thread 0x7f4ecdf1f640 (LWP 26883) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ebc0028e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7f4f297fa640 (LWP 23411) 0x00007f4f36d2f7ef in __GI___poll (fds=0x5585e6942b10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  13   Thread 0x7f4f28ff9640 (LWP 23412) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4f0c00f810, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  14   Thread 0x7f4ec128a640 (LWP 26887) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4eb8005330, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  15   Thread 0x7f4f2b7fe640 (LWP 23407) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4f10004e60, nfds=1, timeout=900474) at ../sysdeps/unix/sysv/linux/poll.c:29
  16   Thread 0x7f4ef65dc640 (LWP 23421) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4edc004240, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  17   Thread 0x7f4f29ffb640 (LWP 27813) futex_abstimed_wait_cancelable (private=0, abstime=0x7f4f29ffab00, clockid=<optimized out>, expected=0, futex_word=0x5585e69dc784)
    at ../sysdeps/nptl/futex-internal.h:320
  18   Thread 0x7f4ecef21640 (LWP 28022) futex_wait_cancelable (private=0, expected=0, futex_word=0x5585e8e10670) at ../sysdeps/nptl/futex-internal.h:183
  19   Thread 0x7f4ef7fff640 (LWP 27809) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ef7ffeae0, nfds=1, timeout=1000) at ../sysdeps/unix/sysv/linux/poll.c:29
  20   Thread 0x7f4ef5ddb640 (LWP 23422) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ed4003a10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  21   Thread 0x7f4ef48c7640 (LWP 23424) 0x00007f4f36d2f7ef in __GI___poll (fds=0x7f4ec4003e10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  22   Thread 0x7f4f33b3f980 (LWP 23401) 0x00007f4f36d2f7ef in __GI___poll (fds=0x5585e69bea60, nfds=5, timeout=9) at ../sysdeps/unix/sysv/linux/poll.c:29
  23   Thread 0x7f4eff816640 (LWP 27812) futex_abstimed_wait_cancelable (private=0, abstime=0x7f4eff815b00, clockid=<optimized out>, expected=0, futex_word=0x5585e6dca6c4)
    at ../sysdeps/nptl/futex-internal.h:320
  24   Thread 0x7f4efe7fc640 (LWP 27810) futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5585e8f1ac90) at ../sysdeps/nptl/futex-internal.h:320
  25   Thread 0x7f4eb7fff640 (LWP 28024) 0x00007f4f370bd910 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) ()
   from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f4f36c63536 in __GI_abort () at abort.c:79
#2  0x00007f4f36cbab3e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f4f36dc4b9b "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f4f36cc24ea in malloc_printerr (str=str@entry=0x7f4f36dc7440 "malloc(): invalid size (unsorted)") at malloc.c:5389
#4  0x00007f4f36cc57cc in _int_malloc (av=av@entry=0x7f4ee8000020, bytes=bytes@entry=88) at malloc.c:3764
#5  0x00007f4f36cc7059 in __GI___libc_malloc (bytes=88) at malloc.c:3086
#6  0x00007f4f3701ff25 in operator new(unsigned long) () at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
#7  0x00005585e4354d44 in  ()
#8  0x00005585e435350e in  ()
#9  0x00005585e40742fe in  ()
#10 0x00005585e423b87e in  ()
#11 0x00005585e423c856 in  ()
#12 0x00005585e423dcf4 in  ()
#13 0x00005585e423de08 in  ()
#14 0x00007f4f3b40cf5e in start_thread (arg=0x7f4ec0a89640) at pthread_create.c:463
#15 0x00007f4f36d3a2bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by gyakovlev** [comment]
looks like it's not really apulse related, just got a report of similar failure with pulseaudio.

https://bugs.gentoo.org/754012

webrtc-less build is unofficial and  unsupported, idk if someone here is interested in fixing it.

**Comment by Hummer12007** [comment]
It was a build with WebRTC, for the record.

**Comment by ilya-fedin** [comment]
> Hm, calls crash for me with this solution

WebRTC doesn't support fallbacks. When it is built with pulseaudio, it will use only pulseaudio and crash without it due to a RTC_CHECK that checks for a working ADM backend.

Unfortunately, built-in ADM backends are only for test purposes (that's why there's no such a basic thing) and tdesktop should implement its own, but AFAIK @john-preston has no time for this and this won't be implemented any time soon.

**Comment by john-preston** [comment]
Right now Telegram Desktop uses its own AudioDeviceModule implemented using OpenAL (as all other sound in TDesktop works). So I think this is irrelevant now.
